version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore src/OpenTracing.Contrib.NetStandard.csproj
      - run: dotnet build src/OpenTracing.Contrib.NetStandard.csproj
      - run: dotnet test src/OpenTracing.Contrib.NetStandard.csproj --no-build
      - run: dotnet pack src/OpenTracing.Contrib.NetStandard.csproj --no-build --output nupkgs
